# Generated by Django 5.0 on 2023-12-11 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbody',
            name='str',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='responsebody',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 14, 37, 14, 169318)),
        ),
        migrations.AddField(
            model_name='responsebody',
            name='method',
            field=models.CharField(default='GET'),
        ),
        migrations.AddField(
            model_name='responsebody',
            name='statuscode',
            field=models.IntegerField(default=404),
        ),
        migrations.AddField(
            model_name='responsebody',
            name='uri',
            field=models.URLField(default='ya.ru'),
        ),
    ]
